### 댓글 전체 조회
GET http://localhost:8080/boards/21/comments
Authorization: Bearer eyJkYXRlIjoxNzE2NzQzMjU4NjQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDtkZwiLCJkZXBObyI6MywiaW1nVXJsIjoiNTdiMzMzYzRhZTg5NGM2ZGFhODIxODkwZWQ4OTdkNDkucG5nIiwibWVtYmVyTm8iOiIzIiwicG9zaXRpb25MZXZlbCI6Mywic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDMiLCJyb2xlIjoiTFYzIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuydtOynhOyasCIsInBvc2l0aW9uTm8iOjMsImV4cCI6MTcxNjgyOTY1OCwiZGVwTmFtZSI6Iuq4sO2aje2MgCJ9.bPM-gSraO3-CssZ7R5o8xZPrv1FbXsZQoyiDQM99K6s

### 특정 댓글 조회
GET http://localhost:8080/boards/21/comments/3
Authorization: Bearer eyJkYXRlIjoxNzE2NTE5OTA1NTEyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwiaW1nVXJsIjoiY2M1Njg0YjVmMDliNGIwNjhiM2JkZTFjNmU5YTBkZjkucG5nIiwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjYwNjMwNSwiZGVwTmFtZSI6IuuyleustO2MgCJ9.3Rk1DUYWYCJvhYgDJ4SBwOREoGzWKogQ20V5b0lQjcA

### 댓글 등록
POST http://localhost:8080/boards/21/comments
Authorization: Bearer eyJkYXRlIjoxNzE2NTE5OTA1NTEyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwiaW1nVXJsIjoiY2M1Njg0YjVmMDliNGIwNjhiM2JkZTFjNmU5YTBkZjkucG5nIiwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjYwNjMwNSwiZGVwTmFtZSI6IuuyleustO2MgCJ9.3Rk1DUYWYCJvhYgDJ4SBwOREoGzWKogQ20V5b0lQjcA
Content-Type: application/json

{
  "memberNo": "5",
  "commentContent": "댓글 등록2"
}

### 대댓글 등록 (POST http://localhost:8080/boards/{boardNo}/comments/{parentCommentId}/replies)
POST http://localhost:8080/boards/21/comments/2/replies
Authorization: Bearer eyJkYXRlIjoxNzE2NzM4MjQ3NDk0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwiaW1nVXJsIjoiY2M1Njg0YjVmMDliNGIwNjhiM2JkZTFjNmU5YTBkZjkucG5nIiwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjgyNDY0NywiZGVwTmFtZSI6IuuyleustO2MgCJ9.rAbTAikL2_Gtk1-mdOqdngQquVOQrvS4R1ThhYyuyD8
Content-Type: application/json

{
  "memberNo": "3",
  "commentContent": "대댓글 등록"
}

### 댓글 수정
PUT http://localhost:8080/boards/21/comments/3
Authorization: Bearer eyJkYXRlIjoxNzE2NTE5OTA1NTEyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwiaW1nVXJsIjoiY2M1Njg0YjVmMDliNGIwNjhiM2JkZTFjNmU5YTBkZjkucG5nIiwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjYwNjMwNSwiZGVwTmFtZSI6IuuyleustO2MgCJ9.3Rk1DUYWYCJvhYgDJ4SBwOREoGzWKogQ20V5b0lQjcA
Content-Type: application/json

{
  "commentContent": "대댓글 수정"
}

### 댓글 삭제
DELETE http://localhost:8080/boards/21/comments/3
Authorization: Bearer eyJkYXRlIjoxNzE2NTE5OTA1NTEyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwiaW1nVXJsIjoiY2M1Njg0YjVmMDliNGIwNjhiM2JkZTFjNmU5YTBkZjkucG5nIiwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjYwNjMwNSwiZGVwTmFtZSI6IuuyleustO2MgCJ9.3Rk1DUYWYCJvhYgDJ4SBwOREoGzWKogQ20V5b0lQjcA


