### 메일 작성
POST http://localhost:8080/mails
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE2MTc0NDY3MDU2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiNTVhN2NlM2I0MTk1NGY5MmI2ODYzMWU5MDQ0ZTM1NDAucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI2MDg2NywiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.1zGavVEjTBTqnFC85muOtXlSQRdtV7K03VovnHKDFhQ
Accept: */*

--WebAppBoundary
Content-Disposition: form-data; name="mailDto"
Content-Type: application/json

{
  "mailTitle": "메일 테스트1",
  "mailContent": "테스트1",
  "replyMailNo": 0,
  "receivers": [
     {"receiverMem":  "2"}
  ]
}

--WebAppBoundary
Content-Disposition: form-data; name="mailFile"; filename="pikachu.png"

< ./pikachu.png
--WebAppBoundary--

### 보낸 메일 조회 & 제목 검색 & 작성자 검색
GET http://localhost:8080/mails?part=send
Authorization: Bearer eyJkYXRlIjoxNzE1MjI0MzU0MDk3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NCwibWVtYmVyTm8iOiI0IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDQiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuy1nOyKueyasSIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTMxMDc1NH0.kR8UUHy5v8VOqQhA8b_ijS64xhXvuc-kcCsoTfH4zM4

### 받은 메일 조회
GET http://localhost:8080/mails?part=receive&search=mailTitle&searchvalue=사과
Authorization: Bearer eyJkYXRlIjoxNzE2MTQxNTE3NjI1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiNTVhN2NlM2I0MTk1NGY5MmI2ODYzMWU5MDQ0ZTM1NDAucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjIyNzkxNywiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.xmq9C5OcehmM0rVCXG0paMnLm4ZoybY2QdKGHdW32ow

### 메일 상세 조회
GET http://localhost:8080/mails/21
Authorization: Bearer eyJkYXRlIjoxNzE1NzY0OTczNjAwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwiaW1nVXJsIjoiY2M1Njg0YjVmMDliNGIwNjhiM2JkZTFjNmU5YTBkZjkucG5nIiwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTg1MTM3MywiZGVwTmFtZSI6IuuyleustO2MgCJ9.Hn3t4D11M0ifwxItJo5OoBEmVAuaMilFU3zVEwwZlwQ

### 발송 취소
PUT http://localhost:8080/mails/11
Authorization: Bearer eyJkYXRlIjoxNzE0NjMwNDA2NjYzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDtkZwiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Mywic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYzIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE2ODA2fQ.k0Qbmy4NR8qm0zZQ8dOHF1UHNBn5v8CLur3PBlhGXQo

### 보낸 메일 삭제
PUT http://localhost:8080/mails?part=send&mailno=40&mailno=47
Authorization: Bearer eyJkYXRlIjoxNzE1ODUwNzA5MTU5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiNTVhN2NlM2I0MTk1NGY5MmI2ODYzMWU5MDQ0ZTM1NDAucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTkzNzEwOSwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.1kib7DGaWcQbWU46cJ1ia3SPR_KJRXgM-E3Kfn4sorE

### 받은 메일 삭제
PUT http://localhost:8080/mails?part=receive&mailno=2&mailno=11
Authorization: Bearer eyJkYXRlIjoxNzE1NTkyOTQxNzU2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiNTVhN2NlM2I0MTk1NGY5MmI2ODYzMWU5MDQ0ZTM1NDAucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTY3OTM0MSwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.oMEhx9uvRFMYeA-ZsFF2UMSXJGlUpIWqmqZopdRQ_e0

### 메일 답장
POST http://localhost:8080/mails/4/reply
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE0NzA4OTI3MzQzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0Nzk1MzI3fQ.dgXytZomTZM8G2PGmgRjADEwT0uRBeb0kHOKaOi9dsM

--WebAppBoundary
Content-Disposition: form-data; name="mailInfo"
Content-Type: application/json

{
  "mailContent": "답장보냅니다."
}

--WebAppBoundary
Content-Disposition: form-data; name="mailFile"; filename="pikachu.png"

< ./pikachu.png
--WebAppBoundary--

### 메일 읽음
PUT http://localhost:8080/mails/times/39
Authorization: Bearer eyJkYXRlIjoxNzE1Njc0MTY2MzQyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwiaW1nVXJsIjoiY2M1Njg0YjVmMDliNGIwNjhiM2JkZTFjNmU5YTBkZjkucG5nIiwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTc2MDU2NiwiZGVwTmFtZSI6IuuyleustO2MgCJ9.NVEemTCgPClB5-M4ytUMVaquqTtmmhZZXgsj2VykWCU
