### 공지 push 전달용
GET http://localhost:8080/notices
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

### 공지 목록 조회
GET http://localhost:8080/notices
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

### 공지 목록 조회 / 제목 검색
GET http://localhost:8080/notices?title="공지 제목1"
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

### 공지 상세 조회
GET http://localhost:8080/notices/1
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

### 공지 등록
POST http://localhost:8080/notices
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

--WebAppBoundary
Content-Disposition: form-data; name="noticeDTO"
Content-Type: application/json

{
  "noticeTitle": "공지제목검색용",
  "noticeContent": "공지 내용1",
    "noticeFix": "N"
}
--WebAppBoundary--

### 공지 등록(첨부파일)
POST http://localhost:8080/notices
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

--WebAppBoundary
Content-Disposition: form-data; name="noticeDTO"
Content-Type: application/json

{
  "noticeTitle": "공지 제목1",
  "noticeContent": "공지 내용1",
  "noticeFix": "N"
}
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="pikachu.png"

< ./pikachu.png
--WebAppBoundary--

### 공지 수정
PUT http://localhost:8080/notices/12
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

--WebAppBoundary
Content-Disposition: form-data; name="noticeDTO"
Content-Type: application/json

{
  "noticeTitle": "공지 제목 수정수정",
  "noticeContent": "공지 내용 수정수정",
  "noticeFix": "Y"
}
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="pikachu.png"

< ./pikachu.png
--WebAppBoundary--

### 공지 삭제
DELETE http://localhost:8080/notices/2
Authorization: Bearer eyJkYXRlIjoxNzE0NjMyMjQyMjQ3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NzE4NjQyfQ.D06Qo5a_7XHSH0vEUVeGtx3E5dg9Sq5C5ZdvCm4wDJ8

