### 공지 push 전달용
GET http://localhost:8080/notices

### 공지 목록 조회
GET http://localhost:8080/notices
Authorization: Bearer eyJkYXRlIjoxNzE0NDQxNzk0MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NTI4MTk0fQ.5JITGBG7ArGwl2__H1zwix9ikX-0_alYsw4WD1KKQmY

### 공지 목록 조회 / 제목 검색
GET http://localhost:8080/notices?title=""
Authorization: Bearer eyJkYXRlIjoxNzE0NDQxNzk0MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NTI4MTk0fQ.5JITGBG7ArGwl2__H1zwix9ikX-0_alYsw4WD1KKQmY

### 공지 상세 조회
GET http://localhost:8080/notices/1
Authorization: Bearer eyJkYXRlIjoxNzE0NDQxNzk0MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NTI4MTk0fQ.5JITGBG7ArGwl2__H1zwix9ikX-0_alYsw4WD1KKQmY

### 공지 등록
POST http://localhost:8080/notices
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE0NDQxNzk0MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NTI4MTk0fQ.5JITGBG7ArGwl2__H1zwix9ikX-0_alYsw4WD1KKQmY

--WebAppBoundary
Content-Disposition: form-data; name="noticeDTO"
Content-Type: application/json

{
  "noticeTitle": "공지제목검색용",
  "noticeContent": "공지 내용1",
    "noticeFix": "N"
}

--WebAppBoundary--

### 공지 등록(첨부파일)
POST http://localhost:8080/notices
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE0NDQxNzk0MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NTI4MTk0fQ.5JITGBG7ArGwl2__H1zwix9ikX-0_alYsw4WD1KKQmY

--WebAppBoundary
Content-Disposition: form-data; name="noticeDTO"
Content-Type: application/json

{
  "noticeTitle": "공지 제목1",
  "noticeContent": "공지 내용1",
  "noticeFix": "N"
}

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test1"
Content-Type: text/plain
### Content-Type: image/png

This is the content of the test-file.
--WebAppBoundary--

### 공지 수정
PUT http://localhost:8080/notices/13
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJkYXRlIjoxNzE0NDQxNzk0MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NTI4MTk0fQ.5JITGBG7ArGwl2__H1zwix9ikX-0_alYsw4WD1KKQmY

--WebAppBoundary
Content-Disposition: form-data; name="noticeDTO"
Content-Type: application/json

{
  "noticeTitle": "공지 제목 수정수정",
  "noticeContent": "공지 내용 수정수정",
  "noticeFix": "Y"
}

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="test1.1"
Content-Type: text/plain
### Content-Type: image/png

This is the content of the test-file.
--WebAppBoundary--

### 공지 삭제
DELETE http://localhost:8080/notices/13
Authorization: Bearer eyJkYXRlIjoxNzE0NDQxNzk0MTI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwicG9zaXRpb25ObyI6MiwiZXhwIjoxNzE0NTI4MTk0fQ.5JITGBG7ArGwl2__H1zwix9ikX-0_alYsw4WD1KKQmY


