### 자원 예약 목록 조회
GET http://localhost:8080/reserves?category=회의실&date=2024-05-10
Authorization: Bearer eyJkYXRlIjoxNzE2MDM4ODgyODMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDtkZwiLCJkZXBObyI6MywiaW1nVXJsIjoiNTdiMzMzYzRhZTg5NGM2ZGFhODIxODkwZWQ4OTdkNDkucG5nIiwibWVtYmVyTm8iOiIzIiwicG9zaXRpb25MZXZlbCI6Mywic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDMiLCJyb2xlIjoiTFYzIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuydtOynhOyasCIsInBvc2l0aW9uTm8iOjMsImV4cCI6MTcxNjEyNTI4MiwiZGVwTmFtZSI6Iuq4sO2aje2MgCJ9.O-b_H0M63bd2LBtMYPnaWbKYrn6qf6Fb8NaZvSsTaI8

### 자원 예약 상세 조회
GET http://localhost:8080/reserves/1
Authorization: Bearer eyJkYXRlIjoxNzE1OTExNDg1NjUwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDtkZwiLCJkZXBObyI6MywiaW1nVXJsIjoiNTdiMzMzYzRhZTg5NGM2ZGFhODIxODkwZWQ4OTdkNDkucG5nIiwibWVtYmVyTm8iOiIzIiwicG9zaXRpb25MZXZlbCI6Mywic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDMiLCJyb2xlIjoiTFYzIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuydtOynhOyasCIsInBvc2l0aW9uTm8iOjMsImV4cCI6MTcxNTk5Nzg4NSwiZGVwTmFtZSI6Iuq4sO2aje2MgCJ9.CFwOMn4gM8_GSetxzekIMZ7MDDMM281nLuZXMv32BYA

### 자원 예약 등록
POST http://localhost:8080/reserves
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE1OTExNDg1NjUwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDtkZwiLCJkZXBObyI6MywiaW1nVXJsIjoiNTdiMzMzYzRhZTg5NGM2ZGFhODIxODkwZWQ4OTdkNDkucG5nIiwibWVtYmVyTm8iOiIzIiwicG9zaXRpb25MZXZlbCI6Mywic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDMiLCJyb2xlIjoiTFYzIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuydtOynhOyasCIsInBvc2l0aW9uTm8iOjMsImV4cCI6MTcxNTk5Nzg4NSwiZGVwTmFtZSI6Iuq4sO2aje2MgCJ9.CFwOMn4gM8_GSetxzekIMZ7MDDMM281nLuZXMv32BYA

{
  "rsvStartDttm": "2024-05-10 오후 6시 0분",
  "rsvEndDttm": "2024-05-10 오후 7시 30분",
  "rsvDescr": "회의실C 한번더 추가",
  "reserver": "5",
  "resources": {
    "rscNo": 4,
    "rscCategory": "회의실",
    "rscName": "회의실 C",
    "rscInfo": "3층 303호",
    "rscCap": 8,
    "rscIsAvailable": true,
    "rscDescr": "Smart TV, 빔프로젝터, 책상, 의자, 단상 비치, 경복궁 뷰, 이곳은 천국"
  }
}

### 자원 예약 수정
PUT http://localhost:8080/reserves/39
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE1OTA3MTkyMDUwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDtkZwiLCJkZXBObyI6MywiaW1nVXJsIjoiNTdiMzMzYzRhZTg5NGM2ZGFhODIxODkwZWQ4OTdkNDkucG5nIiwibWVtYmVyTm8iOiIzIiwicG9zaXRpb25MZXZlbCI6Mywic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDMiLCJyb2xlIjoiTFYzIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuydtOynhOyasCIsInBvc2l0aW9uTm8iOjMsImV4cCI6MTcxNTk5MzU5MiwiZGVwTmFtZSI6Iuq4sO2aje2MgCJ9.X7Q3ybvfVv8YRaBFK8o4XK1kPNgDUw9jIyxKoQ9x6d4

{
  "rsvDescr": "rsvNo 6 예약건 수정의 건",
  "rsvStartDttm": "2024-05-08 오후 1시 0분",
  "rsvEndDttm": "2024-05-08 오후 1시 30분"
}

### 자원 예약 삭제
DELETE http://localhost:8080/reserves/6
Authorization: Bearer eyJkYXRlIjoxNzE1OTA3MTkyMDUwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLrjIDtkZwiLCJkZXBObyI6MywiaW1nVXJsIjoiNTdiMzMzYzRhZTg5NGM2ZGFhODIxODkwZWQ4OTdkNDkucG5nIiwibWVtYmVyTm8iOiIzIiwicG9zaXRpb25MZXZlbCI6Mywic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDMiLCJyb2xlIjoiTFYzIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuydtOynhOyasCIsInBvc2l0aW9uTm8iOjMsImV4cCI6MTcxNTk5MzU5MiwiZGVwTmFtZSI6Iuq4sO2aje2MgCJ9.X7Q3ybvfVv8YRaBFK8o4XK1kPNgDUw9jIyxKoQ9x6d4



