### 자원 예약 목록 조회
GET http://localhost:8080/reserves?category=회의실&date=2024-05-10
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

### 자원 예약 상세 조회
GET http://localhost:8080/reserves/1
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

### 자원 예약 등록
POST http://localhost:8080/reserves
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

{
  "rsvStartDttm": "2024-05-10 오후 9시 30분",
  "rsvEndDttm": "2024-05-10 오후 10시 30분",
  "rsvDescr": "회의실B 예약 2",
  "reserver": "5",
  "resources": {
    "rscNo": 2
  }
}

### 자원 예약 수정
PUT http://localhost:8080/reserves/6
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

{
  "rsvDescr": "회의실C",
  "rsvStartDttm": "2024-05-10 오후 6시 30분",
  "rsvEndDttm": "2024-05-10 오후 7시 30분",
  "resources" : {
    "rscNo": 3
  }
}

### 자원 예약 삭제
DELETE http://localhost:8080/reserves/6
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94



