### 자원 등록
POST http://localhost:8080/resources
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

{
  "rscCategory" : "차량",
  "rscName" : "법인차량3",
  "rscInfo" : "03다 3333",
  "rscCap" : 9,
  "rscIsAvailable" : false
}

### 자원 목록 조회
GET http://localhost:8080/resources?part=conferences
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

### 자원 상세 조회
GET http://localhost:8080/resources/4
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

### 자원 수정
PUT http://localhost:8080/resources/2
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94

{
  "rscIsAvailable" : true,
  "rscDescr" : "비고 수정합니다."
}

### 자원 삭제
DELETE http://localhost:8080/resources/1
Authorization: Bearer eyJkYXRlIjoxNzE2MTY3NjM4NDk1LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6MiwiaW1nVXJsIjoiYzExNDc3MzJkNmMxNDk2OThmOGI0ZGM2NjVmMzlmZTcucG5nIiwibWVtYmVyTm8iOiIyIiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDIiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6IuuwleuLpOydgCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNjI1NDAzOCwiZGVwTmFtZSI6IuyduOyCrO2MgCJ9.wd5oq59nf_ovgm9kGMN8bhTCB0_irZoLFWBNQVGHG94
