### 부서별 일정 목록 조회
GET http://localhost:8080/schedules/department/5
Authorization: Bearer eyJkYXRlIjoxNzE1MzEzMTY2MTM0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTM5OTU2NiwiZGVwTmFtZSI6IuuyleustO2MgCJ9.CHW7Wcan5z8QwyMGDsaPbUr0vsKHv0SST5Qu1rL2GhQ

### 부서별 일정 상세 조회
GET http://localhost:8080/schedules/department/5/schedules/102
Authorization: Bearer eyJkYXRlIjoxNzE1MzEzMTY2MTM0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTM5OTU2NiwiZGVwTmFtZSI6IuuyleustO2MgCJ9.CHW7Wcan5z8QwyMGDsaPbUr0vsKHv0SST5Qu1rL2GhQ

### 부서별 일정 등록
POST http://localhost:8080/schedules/schedules
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE1MzEzMTY2MTM0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTM5OTU2NiwiZGVwTmFtZSI6IuuyleustO2MgCJ9.CHW7Wcan5z8QwyMGDsaPbUr0vsKHv0SST5Qu1rL2GhQ

{
  "skdNo": 102,
  "dptNo": 5,
  "skdName": "scheduleRestAPI에서 보내는 일정2",
  "skdStartDttm": "2024-05-10 18:00",
  "skdEndDttm": "2024-05-10 20:00",
  "skdLocation": "코스트코 광명점 5층 ㅇㅅㅇ 부장실",
  "skdMemo": "새로 등록한 일정이 정상적으로 반영되었습니다."
}

### 부서별 일정 수정
PUT http://localhost:8080/schedules/schedules/50
Content-Type: application/json
Authorization: Bearer eyJkYXRlIjoxNzE1MzEzMTY2MTM0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTM5OTU2NiwiZGVwTmFtZSI6IuuyleustO2MgCJ9.CHW7Wcan5z8QwyMGDsaPbUr0vsKHv0SST5Qu1rL2GhQ

{
  "skdName": "김동환 수정본",
  "skdStartDttm": "2024-12-25 오전 10시 0분",
  "skdEndDttm": "2024-12-25 오후 7시 0분",
  "skdLocation": "효자로 15길 다모여빌딩",
  "skdMemo": "수정한 일정이 정상적으로 반영되었습니다."
}

### 부서별 일정 삭제
DELETE http://localhost:8080/schedules/schedules/2
Authorization: Bearer eyJkYXRlIjoxNzE1MzEzMTY2MTM0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJwb3NpdGlvbk5hbWUiOiLtjIDsnqUiLCJkZXBObyI6NSwibWVtYmVyTm8iOiI1IiwicG9zaXRpb25MZXZlbCI6Miwic3ViIjoia2V0Y2h1cCB0b2tlbiA6IDUiLCJyb2xlIjoiTFYyIiwicG9zaXRpb25TdGF0dXMiOiJZIiwibWVtYmVyTmFtZSI6Iuq5gO2YhOyngCIsInBvc2l0aW9uTm8iOjIsImV4cCI6MTcxNTM5OTU2NiwiZGVwTmFtZSI6IuuyleustO2MgCJ9.CHW7Wcan5z8QwyMGDsaPbUr0vsKHv0SST5Qu1rL2GhQ
